export const viewAllD = [
  {
    id: 1,
    img: "/AI-Certificatiom-for-pro.png",
    title: "Data Science",
    title1: "Foundation Program",
    para: [
      "225 hours of Interactive Learning",
      "8 Projects + 1 Capstone",
      "Course Fee : ₹ 65,000 + GST",
    ],
    link1: "/data-science-certification-courses",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Data+Science+Foundation+Program.pdf",

  },
  {
    id: 2,
    img: "/Advance-Data-Science-1.png",
    title: "Advanced Data Science",
    title1: "and AI Program",

    para: [
      "275 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 79,000 + GST",
    ],
        link1: "/advance-data-science-certification-courses",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Advance+Data+Science+and+AI+Program.pdf",
  },
  {
    id: 3,
    img: "/AIML.png",
    title: "Advance AI and ML Program",
    title1: "for Tech Professionals",
    para: [
      "300 hours of Interactive Learning",
      "15 Projects + 2 Capstones",
      "Course Fee : ₹ 95,000 + GST",
    ],
        link1: "/artificial-intelligence-certification-course",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Artificial+Intelligence+and+Machine+Learning+Program.pdf",
  },
  {
    id: 4,
    img: "/managers-and-leaders-1.png",
    title: "Data Science and AI for ",
    title1: "Managers & Leaders Program",
    para: [
      "350 hours of Interactive Learning",
      "15 Projects + 2 Capstones",
      "Course Fee : ₹ 95,000 + GST",
    ],
        link1: "/data-science-ai-for-managers",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Data+Science+and+AI+For+Managers+and+Leaders+Program.pdf",
  },
  {
    id: 5,
    img: "/Job-garranty.png",
    title: "Data Science and AI with ",
    title1: "Job Guarantee Program",

    para: [
      "400 hours of Interactive Learning",
      "15 Projects + 3 Capstones",
      "Course Fee : ₹ 1,25,000 + GST",
    ],
        link1: "/job-guarantee-or-money-back-data-science-ai-certification-course",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Data+Science+and+AI+with+100%25+Job+Guarantee.pdf",
  },
  {
    id: 6,
    img: "/Data-Analytics-1.png",
    title: "Data Analytics",
    title1: "Program",
    para: [
      "180 hours of Interactive Learning",
      "5 Projects",
      "Course Fee : ₹ 60,000 + GST",
    ],
        link1: "/data-analytics-certification-course",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Data+Analytics+Program.pdf",
  },
  {
    id: 7,
    img: "/DABA.png",
    title: "Business Analytics",
    title1: "Program",
    para: [
      "200 hours of Interactive Learning",
      "5 Projects",
      "Course Fee : ₹ 65,000 + GST",
    ],
        link1: "/business-analytics-certification-course",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Business+Analytics+Program.pdf",
  },
  {
    id: 8,
    img: "/full-stack-web.png",
    title: "Full-Stack Web ",
    title1: "Development Program",
    para: [
      "350 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 1,20,000 + GST",
    ],
        link1: "/full-stack-web-development-program",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Full+Stack+Web+Development+Program+(1).pdf",
  },
  {
    id: 9,
    img: "/full-stack-Software.png",
    title: "Full-Stack Software",
    title1: "Development Program",
    para: [
      "400 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 1,10,000 + GST",
    ],
        link1: "/full-stack-software-development-program",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Advanced+Software+Development+Program.pdf",
  },
];
export const ForProgrammersD = [
  {
    id: 1,
    img: "/Advance-Data-Science-1.png",
    title: "Advanced Data Science",
    title1: "and AI Program",
    para: [
      "275 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 79,000 + GST",
    ],
        link1: "/advance-data-science-certification-courses",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Advance+Data+Science+and+AI+Program.pdf",
  },
  {
    id: 2,
    img: "/full-stack-Software.png",
    title: "Full-Stack Software",
    title1: "Development Program",
    para: [
      "400 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 1,10,000 + GST",
    ],
        link1: "/full-stack-software-development-program",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Advanced+Software+Development+Program.pdf",
  },
  {
    id: 3,
    img: "/managers-and-leaders-1.png",
    title: "Data Science and AI for ",
    title1: "Managers & Leaders Program",
    para: [
      "350 hours of Interactive Learning",
      "15 Projects + 2 Capstones",
      "Course Fee : ₹ 95,000 + GST",
    ],
        link1: "/data-science-ai-for-managers",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Data+Science+and+AI+For+Managers+and+Leaders+Program.pdf",
  },
  {
    id: 4,
    img: "/AIML.png",
    title: "Advance AI and ML Program",
    title1: "for Tech Professionals",
    para: [
      "300 hours of Interactive Learning",
      "15 Projects + 2 Capstones",
      "Course Fee : ₹ 95,000 + GST",
    ],
        link1: "/artificial-intelligence-certification-course",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Artificial+Intelligence+and+Machine+Learning+Program.pdf",
  },
  {
    id: 5,
    img: "/full-stack-web.png",
    title: "Full-Stack Web ",
    title1: "Development Program",
    para: [
      "350 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 1,20,000 + GST",
    ],
        link1: "/full-stack-web-development-program",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Full+Stack+Web+Development+Program+(1).pdf",
  },
  {
    id: 6,
    img: "/Job-garranty.png",
    title: "Data Science and AI with ",
    title1: "Job Guarantee Program",
    para: [
      "400 hours of Interactive Learning",
      "15 Projects + 3 Capstones",
      "Course Fee : ₹ 1,25,000 + GST",
    ],
        link1: "/job-guarantee-or-money-back-data-science-ai-certification-course",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Data+Science+and+AI+with+100%25+Job+Guarantee.pdf",
  },
];
export const ForNonProgrammerD = [
  {
    id: 1,
    img: "/AI-Certificatiom-for-pro.png",
    title: "Data Science",
    title1: "Foundation Program",
    para: [
      "225 hours of Interactive Learning",
      "8 Projects + 1 Capstone",
      "Course Fee : ₹ 65,000 + GST",
    ],
    link1: "/data-science-certification-courses",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Data+Science+Foundation+Program.pdf",

  },
  {
    id: 2,
    img: "/Advance-Data-Science-1.png",
    title: "Advanced Data Science",
    title1: "and AI Program",

    para: [
      "275 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 79,000 + GST",
    ],
        link1: "/advance-data-science-certification-courses",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Advance+Data+Science+and+AI+Program.pdf",
  },
  {
    id: 3,
    img: "/AIML.png",
    title: "Advance AI and ML Program",
    title1: "for Tech Professionals",
    para: [
      "300 hours of Interactive Learning",
      "15 Projects + 2 Capstones",
      "Course Fee : ₹ 95,000 + GST",
    ],
        link1: "/artificial-intelligence-certification-course",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Artificial+Intelligence+and+Machine+Learning+Program.pdf",
  },
  {
    id: 4,
    img: "/managers-and-leaders-1.png",
    title: "Data Science and AI for ",
    title1: "Managers & Leaders Program",
    para: [
      "350 hours of Interactive Learning",
      "15 Projects + 2 Capstones",
      "Course Fee : ₹ 95,000 + GST",
    ],
        link1: "/data-science-ai-for-managers",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Data+Science+and+AI+For+Managers+and+Leaders+Program.pdf",
  },
  {
    id: 5,
    img: "/Job-garranty.png",
    title: "Data Science and AI with ",
    title1: "Job Guarantee Program",

    para: [
      "400 hours of Interactive Learning",
      "15 Projects + 3 Capstones",
      "Course Fee : ₹ 1,25,000 + GST",
    ],
        link1: "/job-guarantee-or-money-back-data-science-ai-certification-course",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Data+Science+and+AI+with+100%25+Job+Guarantee.pdf",
  },
  {
    id: 6,
    img: "/DABA.png",
    title: "Business Analytics",
    title1: "Program",
    para: [
      "200 hours of Interactive Learning",
      "5 Projects",
      "Course Fee : ₹ 65,000 + GST",
    ],
        link1: "/business-analytics-certification-course",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Business+Analytics+Program.pdf",
  },
];

export const JobGuaranteeD = [
  {
    id: 1,
    img: "/Job-garranty.png",
    title: "Data Science and AI with ",
    title1: "Job Guarantee Program",
    para: [
      "400 hours of Interactive Learning",
      "15 Projects + 3 Capstones",
      "Course Fee : ₹ 1,25,000 + GST",
    ],
        link1: "/job-guarantee-or-money-back-data-science-ai-certification-course",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Data+Science+and+AI+with+100%25+Job+Guarantee.pdf",
  },
  {
    id: 2,
    img: "/full-stack-web.png",
    title: "Full-Stack Web ",
    title1: "Development Program",
    para: [
      "350 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 1,20,000 + GST",
    ],
        link1: "/full-stack-web-development-program",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Full+Stack+Web+Development+Program+(1).pdf",
  },
];
export const StackD = [
  {
    id: 1,
    img: "/full-stack-web.png",
    title: "Full-Stack Web ",
    title1: "Development Program",
    para: [
      "350 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 1,20,000 + GST",
    ],
        link1: "/full-stack-web-development-program",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Full+Stack+Web+Development+Program+(1).pdf",
  },
  {
    id: 2,
    img: "/full-stack-Software.png",
    title: "Full-Stack Software",
    title1: "Development Program",
    para: [
      "400 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 1,10,000 + GST",
    ],
        link1: "/full-stack-software-development-program",
    link2: "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/New+Brochure/Advanced+Software+Development+Program.pdf",
  },
];
