export const viewAllD = [
  {
    id: 1,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/Foundation.png",
    title: "Data Science",
    title1: "Foundation Program",
    courseTime: "5-7 months",
    tag: "Data science",
    tagHead: "For Non-Tech Professionals",
    para: [
      "200+ hours content",
      "4 Foundation",
      "Course Fee : ₹ 79,000 | No cost EMI",
    ],
    link1: "/data-science-certification-courses",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Data+Science+Foundation+Program+Learnbay.pdf",
  },
  {
    id: 2,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/Adv.+DSAI.png",
    title: "Advanced Data Science",
    courseTime: "7-9 months",
    title1: "& AI Program",
    tag: "Data science",
    tagHead: "Become A Domain Specialist",
    para: [
      "250+ hours content",
      "8 Advance + 2 Capstone",
      "Course Fee : ₹ 99,000 | No cost EMI",
    ],
    link1: "/advance-data-science-certification-courses",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Advance+Data+Science+and+AI+Certification+Program+Learnbay.pdf",
  },
  {
    id: 3,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/AIML.png",
    title: "Advance AI & ML Program",
    courseTime: "9-11 months",
    title1: "for Tech Professionals",
    tagHead: "For Working Professional",
    tag: "Data science",
    para: [
      "350+ hours content",
      "10 Advance + 2 Capstone",
      "Course Fee : ₹ 1,10,000 | No cost EMI",
    ],
    link1: "/artificial-intelligence-certification-course",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Advance+AI+%26+ML+Certification+Program+Learnbay.pdf",
  },
  {
    id: 4,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/Managers.png",
    title: "Data Science & AI ",
    title1: "For Managers",
    courseTime: "11-13 months",
    tag: "Data science",
    tagHead: "For Sr. Managers/Team Lead",
    para: [
      "400+ hours content",
      "10 Advance + 3 Capstone",
      "Course Fee : ₹ 1,10,000 | No cost EMI",
    ],
    link1: "/data-science-ai-for-managers",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Data+Science+%26+AI+Certification+Program+For+Managers+%26+Leaders+Learnbay.pdf",
  },
  {
    id: 5,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/DSAI+Master+(1).png",
    title: "Data Science & AI ",
    title1: "Master Program",
    courseTime: "13-15 months",
    tagHead: "Guaranteed Interview Call",
    tag: "Data science",
    para: [
      "500+ hours content",
      "12 Advance + 4 Capstone",
      "Course Fee : ₹ 1,29,000 | No cost EMI",
    ],
    link1: "/data-science-ai-masters-program",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Data+Science+and+AI+Master's+Program+%5BWith+Unlimited+Interview+Calls%5D.pdf",
  },
  {
    id: 6,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/DA.png",
    title: "Data Analytics",
    courseTime: "5-6.5 Months",
    title1: "Program",
    tag: "Data science",
    tagHead: "Work on Real-time Projects",
    para: [
      "180+ hours content",
      "8 Advance + 2 Capstopne",
      "Course Fee : ₹ 79,000 | No cost EMI",
    ],
    link1: "/data-analytics-certification-course",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Data+Analytics+Certification+Program+Learnbay.pdf",
  },
  {
    id: 7,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/BA.png",
    title: "Business Analytics",
    title1: "Master Program",
    courseTime: "7-9 months",
    tag: "Data science",
    tagHead: "Dedicated Mentorship",

    para: [
      "250+ hours content",
      "12 Advance + 2 Capstone",
      "Course Fee : ₹ 1,10,000 | No cost EMI",
    ],
    link1: "/business-analytics-certification-course",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Business+Analytics+Certification+Program+Learnbay.pdf",
  },
  {
    id: 8,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/Web+Dev.png",
    title: "Software Development ",
    courseTime: "8-10 months",
    title1: "in Blockchain",
    tag: "Full stack",
    tagHead: "For Non-Tech Professionals",
    para: [
      "250+ hours content",
      "12 Projects",
      "Course Fee : ₹ 95,000 | No cost EMI",
    ],
    link1: "/software-development-program-with-specialization-in-blockchain",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Software+Development+with+Specialization+in+Blockchain.pdf",
  },
  {
    id: 9,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/SW+dev+(1).png",
    title: "Software Development ",
    courseTime: "9-11 months",
    title1: "Master Program",
    tagHead: "Crack Job Interviews",
    tag: "Full stack",
    para: [
      "300+ hours content",
      "12 Projects",
      "Course Fee : ₹ 1,10,000 | No cost EMI",
    ],
    link1: "/full-stack-software-development-program",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Full+Stack+Software+Development+Program+Learnbay.pdf",
  },
  {
    id: 10,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/DSA.png",
    title: "Software Development in ",
    courseTime: "8-10 months",
    title1: "Cloud Computing & DevOps",
    tagHead: "Be a Product Design Pro",
    tag: "Full stack",
    para: [
      "250+ hours content",
      "12 Projects",
      "Course Fee : ₹ 95,000 | No cost EMI",
    ],
    link1:
      "/software-development-program-with-specialization-in-cloud-computing-&-devops",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Software+Development+with+Specialization+in+Cloud+and+DevOps.pdf",
  },
  {
    id: 11,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/BFSI+(1).png",
    title: "Data Science and AI Program",
    title1: "for BFSI Professionals",
    courseTime: "7-9 months",
    tag: "Data science",
    tagHead: "For BFSI Professionals",
    para: [
      "250+ hours content",
      "10 Advance + 2 Capstone",
      "Course Fee : ₹ 89,000 | No cost EMI",
    ],
    link1: "/banking-finance-analytics",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Data+Analytics+Certification+Program+Learnbay.pdf",
  },
  {
    id: 12,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/HR.png",
    title: "HR Analytics",
    courseTime: "5-7 months",
    title1: "Program",
    tag: "Data science",
    tagHead: "Leadership Role In HR Domain",
    para: [
      "200+ hours content",
      "10 Advance + 2 Capstone",
      "Course Fee : ₹ 89,000 | No cost EMI",
    ],
    link1: "/hr-analytics",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Data+Analytics+Certification+Program+Learnbay.pdf",
  },
  {
    id: 13,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/Marketing.png",
    title: "Marketing Analytics",
    courseTime: "5-7 months",
    title1: "Program",
    tag: "Data science",
    tagHead: "Excel data-driven marketing",
    para: [
      "200+ hours content",
      "10 Advance + 2 Capstone",
      "Course Fee : ₹ 89,000 | No cost EMI",
    ],
    link1: "/marketing-analytics",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Data+Analytics+Certification+Program+Learnbay.pdf",
  },
];
export const ForProgrammersD = [
  {
    id: 1,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/Adv.+DSAI.png",
    title: "Advanced Data Science",
    courseTime: "7-9 months",
    title1: "& AI Program",
    tag: "Data science",
    tagHead: "Become A Domain Specialist",
    para: [
      "250+ hours content",
      "8 Advance + 2 Capstone",
      "Course Fee : ₹ 99,000 | No cost EMI",
    ],
    link1: "/advance-data-science-certification-courses",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Advance+Data+Science+and+AI+Certification+Program+Learnbay.pdf",
  },
  {
    id: 2,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/SW+dev+(1).png",
    title: "Software Development ",
    courseTime: "9-11 months",
    title1: "Master Program",
    tagHead: "Crack Job Interviews",
    tag: "Full stack",
    para: [
      "300+ hours content",
      "12 Projects",
      "Course Fee : ₹ 1,10,000 | No cost EMI",
    ],
    link1: "/full-stack-software-development-program",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Full+Stack+Software+Development+Program+Learnbay.pdf",
  },
  {
    id: 3,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/Managers.png",
    title: "Data Science & AI ",
    title1: "For Managers",
    courseTime: "11-13 months",
    tag: "Data science",
    tagHead: "For Sr. Managers/Team Lead",
    para: [
      "400+ hours content",
      "10 Advance + 3 Capstone",
      "Course Fee : ₹ 1,10,000 | No cost EMI",
    ],
    link1: "/data-science-ai-for-managers",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Data+Science+%26+AI+Certification+Program+For+Managers+%26+Leaders+Learnbay.pdf",
  },
  {
    id: 4,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/AIML.png",
    title: "Advance AI & ML Program",
    courseTime: "9-11 months",
    title1: "for Tech Professionals",
    tagHead: "For Working Professional",
    tag: "Data science",
    para: [
      "350+ hours content",
      "10 Advance + 2 Capstone",
      "Course Fee : ₹ 1,10,000 | No cost EMI",
    ],
    link1: "/artificial-intelligence-certification-course",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Advance+AI+%26+ML+Certification+Program+Learnbay.pdf",
  },
  {
    id: 5,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/Web+Dev.png",
    title: "Software Development ",
    courseTime: "8-10 months",
    title1: "in Blockchain",
    tag: "Full stack",
    tagHead: "For Non-Tech Professionals",
    para: [
      "250+ hours content",
      "12 Projects",
      "Course Fee : ₹ 95,000 | No cost EMI",
    ],
    link1: "/software-development-program-with-specialization-in-blockchain",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Software+Development+with+Specialization+in+Blockchain.pdf",
  },
  {
    id: 6,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/DSAI+Master+(1).png",
    title: "Data Science & AI ",
    title1: "Master Program",
    courseTime: "13-15 months",
    tagHead: "Guaranteed Interview Call",
    tag: "Data science",
    para: [
      "500 + hours content",
      "12 Advance + 4 Capstone",
      "Course Fee : ₹ 1,29,000 | No cost EMI",
    ],
    link1: "/data-science-ai-masters-program",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Data+Science+and+AI+Master's+Program+%5BWith+Unlimited+Interview+Calls%5D.pdf",
  },
  {
    id: 7,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/DSA.png",
    title: "Software Development in ",
    courseTime: "8-10 months",
    title1: "Cloud Computing & DevOps",
    tagHead: "Be a Product Design Pro",
    tag: "Full stack",
    para: [
      "250+ hours content",
      "12 Projects",
      "Course Fee : ₹ 95,000 | No cost EMI",
    ],
    link1:
      "/software-development-program-with-specialization-in-cloud-computing-&-devops",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Software+Development+with+Specialization+in+Cloud+and+DevOps.pdf",
  },
];
export const ForNonProgrammerD = [
  {
    id: 1,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/Foundation.png",
    title: "Data Science",
    title1: "Foundation Program",
    courseTime: "5-7 months",
    tag: "Data science",
    tagHead: "For Non-Tech Professionals",
    para: [
      "200+ hours content",
      "4 Foundation",
      "Course Fee : ₹ 79,000 | No cost EMI",
    ],
    link1: "/data-science-certification-courses",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Data+Science+Foundation+Program+Learnbay.pdf",
  },
  {
    id: 2,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/Adv.+DSAI.png",
    title: "Advanced Data Science",
    courseTime: "7-9 months",
    title1: "& AI Program",
    tag: "Data science",
    tagHead: "Become A Domain Specialist",
    para: [
      "250+ hours content",
      "8 Advance + 2 Capstone",
      "Course Fee : ₹ 99,000 | No cost EMI",
    ],
    link1: "/advance-data-science-certification-courses",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Advance+Data+Science+and+AI+Certification+Program+Learnbay.pdf",
  },
  {
    id: 3,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/AIML.png",
    title: "Advance AI & ML Program",
    courseTime: "9-11 months",
    title1: "for Tech Professionals",
    tagHead: "For Working Professional",
    tag: "Data science",
    para: [
      "350+ hours content",
      "10 Advance + 2 Capstone",
      "Course Fee : ₹ 1,10,000 | No cost EMI",
    ],
    link1: "/artificial-intelligence-certification-course",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Advance+AI+%26+ML+Certification+Program+Learnbay.pdf",
  },
  {
    id: 4,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/Managers.png",
    title: "Data Science & AI ",
    title1: "For Managers",
    courseTime: "11-13 months",
    tag: "Data science",
    tagHead: "For Sr. Managers/Team Lead",
    para: [
      "400+ hours content",
      "10 Advance + 3 Capstone",
      "Course Fee : ₹ 1,10,000 | No cost EMI",
    ],
    link1: "/data-science-ai-for-managers",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Data+Science+%26+AI+Certification+Program+For+Managers+%26+Leaders+Learnbay.pdf",
  },
  {
    id: 5,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/DSAI+Master+(1).png",
    title: "Data Science & AI ",
    title1: "Master Program",
    courseTime: "13-15 months",
    tag: "Data science",
    tagHead: "Guaranteed Interview Call",
    para: [
      "500+ hours content",
      "12 Advance + 4 Capstone",
      "Course Fee : ₹ 1,29,000 | No cost EMI",
    ],
    link1: "/data-science-ai-masters-program",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Data+Science+and+AI+Master's+Program+%5BWith+Unlimited+Interview+Calls%5D.pdf",
  },
  {
    id: 6,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/BA.png",
    title: "Business Analytics",
    title1: "Master Program",
    courseTime: "7-9 months",
    tag: "Data science",
    tagHead: "Dedicated Mentorship",
    para: [
      "250+ hours content",
      "12 Advance + 4 Capstone",
      "Course Fee : ₹ 1,10,000 | No cost EMI",
    ],
    link1: "1,10usiness-analytics-certification-course",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Business+Analytics+Certification+Program+Learnbay.pdf",
  },
  {
    id: 7,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/DA.png",
    title: "Data Analytics",
    courseTime: "5-6.5 Months",
    title1: "Program",
    tag: "Data science",
    tagHead: "Work on Real-time Projects",
    para: [
      "180+ hours content",
      "8 Advance + 2 Capstopne",
      "Course Fee : ₹ 79,000 | No cost EMI",
    ],
    link1: "/data-analytics-certification-course",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Data+Analytics+Certification+Program+Learnbay.pdf",
  },
  {
    id: 8,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/BFSI+(1).png",
    title: "Data Science and AI Program",
    title1: "for BFSI Professionals",
    courseTime: "7-9 months",
    tag: "Data science",
    tagHead: "For BFSI Professionals",
    para: [
      "250+ hours content",
      "10 Advance + 2 Capstone",
      "Course Fee : ₹ 89,000 | No cost EMI",
    ],
    link1: "/banking-finance-analytics",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Data+Analytics+Certification+Program+Learnbay.pdf",
  },
  {
    id: 9,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/HR.png",
    title: "HR Analytics",
    courseTime: "5-7 months",
    title1: "Program",
    tag: "Data science",
    tagHead: "Leadership Role In HR Domain",
    para: [
      "200+ hours content",
      "10 Advance + 2 Capstone",
      "Course Fee : ₹ 89,000 | No cost EMI",
    ],
    link1: "/hr-analytics",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Data+Analytics+Certification+Program+Learnbay.pdf",
  },
  {
    id: 10,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/Marketing.png",
    title: "Marketing Analytics",
    courseTime: "5-7 months",
    title1: "Program",
    tag: "Data science",
    tagHead: "Excel data-driven marketing",
    para: [
      "200+ hours content",
      "10 Advance + 2 Capstone",
      "Course Fee : ₹ 89,000 | No cost EMI",
    ],
    link1: "/marketing-analytics",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Data+Analytics+Certification+Program+Learnbay.pdf",
  },
];

export const JobGuaranteeD = [
  {
    id: 1,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/DSAI+Master+(1).png",
    title: "Data Science & AI ",
    title1: "Master Program",
    courseTime: "13-15 months",
    tag: "Data science",
    tagHead: "Guaranteed Interview Call",
    para: [
      "500+ hours content",
      "12 Advance + 4 Capstone",
      "Course Fee : ₹ 1,29,000 | No cost EMI",
    ],
    link1: "/data-science-ai-masters-program",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Data+Science+and+AI+Master's+Program+%5BWith+Unlimited+Interview+Calls%5D.pdf",
  },
  {
    id: 2,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/SW+dev+(1).png",
    title: "Software Development ",
    courseTime: "9-11 months",
    title1: "Master Program",
    tagHead: "Crack Job Interviews",
    tag: "Full stack",
    para: [
      "300+ hours content",
      "12 Projects",
      "Course Fee : ₹ 1,10,000 | No cost EMI",
    ],
    link1: "/full-stack-software-development-program",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Full+Stack+Software+Development+Program+Learnbay.pdf",
  },
];
export const StackD = [
  {
    id: 1,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/Web+Dev.png",
    title: "Software Development ",
    courseTime: "8-10 months",
    title1: "in Blockchain",
    tag: "Full stack",
    tagHead: "For Non-Tech Professionals",
    para: [
      "250+ hours content",
      "12 Projects",
      "Course Fee : ₹ 95,000 | No cost EMI",
    ],
    link1: "/software-development-program-with-specialization-in-blockchain",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Software+Development+with+Specialization+in+Blockchain.pdf",
  },
  {
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/SW+dev+(1).png",
    title: "Software Development ",
    courseTime: "9-11 months",
    title1: "Master Program",
    tagHead: "Crack Job Interviews",
    tag: "Full stack",
    para: [
      "300+ hours content",
      "12 Projects",
      "Course Fee : ₹ 1,10,000 | No cost EMI",
    ],
    link1: "/full-stack-software-development-program",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Full+Stack+Software+Development+Program+Learnbay.pdf",
  },
  {
    id: 3,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/Course-home/DSA.png",
    title: "Software Development in ",
    courseTime: "8-10 months",
    title1: "Cloud Computing & DevOps",
    tagHead: "Be a Product Design Pro",
    tag: "Full stack",
    para: [
      "250+ hours content",
      "12 Projects",
      "Course Fee : ₹ 95,000 | No cost EMI",
    ],
    link1:
      "/software-development-program-with-specialization-in-cloud-computing-&-devops",
    link2:
      "https://brochureslearnbay.s3.ap-south-1.amazonaws.com/learnbay/Software+Development+with+Specialization+in+Cloud+and+DevOps.pdf",
  },
];
